[config]
default_to_workspace = false
skip_core_tasks = true

[env]
RUST_TEST_NOCAPTURE=1

[tasks.build]
run_task = [
  {name = "build-development", condition = {profiles = ["development"]}},
  {name = "build-production", condition = {profiles = ["production"]}},
]

[tasks.build-development]
args = ["build"]
command = "anchor"

[tasks.build-production]
args = ["build", "--verifiable"]
command = "anchor"

# Expects a localnet task to be running in background
[tasks.test]
args = ["test", "--test", "token"]
command = "cargo"

[tasks.localnet-reset]
args = [
   "--bpf-program", 
   "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS",
   "target/deploy/account_history_program.so",
   "--reset",
]
command = "solana-test-validator"
dependencies = ["build"]

[tasks.localnet]
args = [
   "--bpf-program", 
   "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS",
   "target/deploy/account_history_program.so",
]
command = "solana-test-validator"
dependencies = ["build"]
