[package]
name = "account-history-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.26.0"
account-history-program = { path = "../programs/account-history-program" }
solana-client = "1.14.16"
solana-sdk = "1.14.16"
thiserror = "1.0.39"
bytemuck = "1.13.1"